# Generated by Django 5.0 on 2023-12-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customuser_user_type_customuser_is_jobseeker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_jobseeker',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_recruiter',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'recruiter'), (2, 'jobseeker')], default=1, max_length=50),
        ),
    ]
