# Generated by Django 5.0 on 2023-12-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_customuser_is_jobseeker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'recruiter'), (2, 'jobseeker')], max_length=50),
        ),
    ]
