# Generated by Django 5.0 on 2023-12-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('jobseeker', 'Jobseeker')], max_length=50),
        ),
    ]
