# Generated by Django 5.0 on 2023-12-12 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number_of_openings', models.IntegerField()),
                ('job_description', models.TextField()),
                ('category', models.CharField(choices=[('IT', 'Information Technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing')], max_length=50)),
                ('jobseeker', models.ManyToManyField(blank=True, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
